#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload
hc keyunbind --all

# Keybindings
Mod=Mod4

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn alacritty

hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5

hc keybind $Mod-Control-space split explode

resizestep=0.02
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

hc keybind $Mod-Alt-s spawn spotify
hc keybind $Mod-Alt-t spawn telegram-desktop
hc keybind $Mod-Alt-b spawn chromium 

# Tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# Layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# Mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# Focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# Theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#212121'
hc set frame_border_normal_color '#212121'
hc set frame_bg_normal_color '#212121'
hc set frame_bg_active_color '#212121'
hc set frame_border_width 0
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#323232'
hc attr theme.normal.color '#323232'
hc attr theme.urgent.color '#323232'
hc attr theme.border_width 32
hc attr theme.inner_width 30
hc attr theme.inner_color '#212121'
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_color '#212121'
hc attr theme.background_color '#212121'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

# Rules
hc unrule -F
hc rule focus=on

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=off
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on

hc rule class=plasmashell floating=on manage=on
hc rule title=plasma-desktop floating=on
hc rule title=win7 floating=on
hc rule class=Plasma floating=on
hc rule class=krunner floating=on
hc rule class=Kmix floating=on
hc rule class=Klipper floating=on
hc rule class=Plasmoidviewer floating=on
hc rule class="(?i)*nextcloud*" floating=on
hc rule windowrole=pop-up floating=on
hc rule windowrole=bubble floating=on
hc rule windowrole=task_dialog floating=on
hc rule windowrole=Preferences floating=on
hc rule windowrole=About floating=on
hc rule windowrole=dialog floating=on
hc rule windowrole=menu floating=on

hc rule class=Spotify tag=3
hc rule class=TelegramDesktop tag=2
hc rule class=chromium tag=1
hc rule class=Thunderbird tag=1

hc set tree_style '╾│ ├└╼─┐'

hc unlock

# Find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    "$panel" "$monitor" &
done


picom &
hc use_index 0
hc split bottom 0.8
hc split right 0.6
hc spawn chromium
sleep 3
hc focus right
hc spawn thunderbird
sleep 3
hc focus down
hc spawn alacritty
sleep 0.5
hc use_index 1
hc split right 0.7
hc spawn alacritty
sleep 0.5
hc focus right
hc spawn telegram-desktop
hc spawn spotify
